export const defaultInitialState = {
  alt: "",
  category: "",
  description: "",
  discontinued: false,
  height: 0,
  id: "00000",
  length: 0,
  name: "",
  price: 0.0,
  src: "",
  stock: 0,
  weight: 0,
  width: 0,
};
