export const ITEM_CONST = {
  name: "NAME",
  stock: "STOCK",
  price: "PRICE",
  alt: "ALT",
  description: "DESCRIPTION",
  src: "SRC",
  length: "LENGTH",
  width: "WIDTH",
  height: "HEIGHT",
  weigth: "WEIGHT",
  category: "CATEGORY",
  discontinued: "DISCONTINUED",
  id: "ID",
  setState: "SETSTATE",
};
